trigger:
    - main
stages:
- stage: 'Build'
  displayName: 'Build app'
  jobs:
  - job: 'Build'
    displayName: 'Build and pack'
    pool:
      vmImage: 'ubuntu-22.04'
    variables:
    - group: wayland
    steps:
    - bash: |
        set -o errexit -o pipefail
        npm ci
        npm run check
        npm run test
        npm run build:prod
      displayName: 'Install, test and build'
    - bash: |
        set -o errexit -o pipefail
        npm pack
        cp *.tgz "$(Build.ArtifactStagingDirectory)"
        cp scripts/nordic-publish.js "$(Build.ArtifactStagingDirectory)"
      condition: ne(variables['Build.Reason'], 'PullRequest')
      displayName: 'Copy artifacts'
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: package
      displayName: 'Publish artifacts to artifact storage'
- stage: 'Internal'
  displayName: 'Release to internal source'
  dependsOn: Build
  condition: ne(variables['Build.Reason'], 'PullRequest')
  jobs:
  - job: 'Release'
    displayName: 'Release to internal'
    pool:
      vmImage: 'ubuntu-22.04'
    variables:
    - group: wayland
    steps:
    - download: current
      artifact: package
    - bash: |
        export REPO_HOST=$(NORDIC_DEVELOPER_HOST)
        export REPO_USER=$(NORDIC_DEVELOPER_USER)
        export REPO_PASS=$(NORDIC_DEVELOPER_PASS)

        cp $(Pipeline.Workspace)/package/* .
        node nordic-publish.js -n -s internal
      displayName: 'Release script'