name: Publish nRF Connect for Desktop

inputs:
    suffix:
        type: string
        required: true

runs:
    using: 'composite'
    steps:
        - name: Pack
          shell: bash
          run: npm pack
        - name: Publish built artifact
          uses: actions/upload-artifact@v4
          with:
              path: ./*.tgz
              retention-days: 3
