parameters:
  - name: environment
    type: string

stages:
- stage: 'Release'
  displayName: $(parameters.environment)
  dependsOn: Build
  condition: ne(variables['Build.Reason'], 'PullRequest')
  jobs:
  - deployment: $(parameters.environment)
    displayName: Deploy to  + $(parameters.environment)
    pool:
      name: wayland_pool_sw_only
      demands:
      - Agent.OS -equals Linux
    variables:
    - group: wayland
    environment: $(parameters.environment)
    strategy:
      runOnce:
        deploy:
          steps:    
          - task: NodeTool@0
            displayName: 'Use Node 18'
            inputs:
              versionSpec: 18.x
          - download: current
            artifact: package
          - bash: |
              export REPO_HOST=$(NORDIC_DEVELOPER_HOST)
              export REPO_USER=$(NORDIC_DEVELOPER_USER)
              export REPO_PASS=$(NORDIC_DEVELOPER_PASS)

              cp $(Pipeline.Workspace)/package/* .
              node nordic-publish.js -n -s $(parameters.environment)
            displayName: 'Release script'