stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build and pack
    pool:
      vmImage: ubuntu-22.04
    variables:
    - group: wayland
    steps:
    - bash: |
        set -o errexit -o pipefail
        npm ci
        npm run check
        npm run test
        npm run build:prod
      displayName: 'Install, test and build'
    - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
      - bash: |
          set -o errexit -o pipefail
          npm pack
          cp *.tgz "$(Build.ArtifactStagingDirectory)"
          cp dist/nordic-publish.js "$(Build.ArtifactStagingDirectory)"
        displayName: 'Copy artifacts'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: package
        displayName: 'Publish artifacts to artifact storage'