
name: Build App

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-action
      - name: Publish artifacts
        uses: ./.github/actions/publish-action
        if: github.event_name != 'pull_request'
