name: Release shared - Test variant that actually unpublishes

on:
    workflow_dispatch:
        inputs:
            marker:
                description: Yes, this is the different version
                required: false
                type: boolean

jobs:
    release:
        uses: ./.github/workflows/create-source.yml
