name: Unpublish npm version - Test variant

on:
    workflow_dispatch:
        inputs:
            version:
                description: Version to unpublish from npm (e.g., 221.0.0)
                required: true
                type: string
            marker:
                description: Yes, this is the different version
                required: false
                type: boolean

jobs:
    unpublish:
        uses: ./.github/workflows/release-shared.yml
        secrets: inherit
        with:
            unpublish: true
            version: ${{ inputs.version }}
            prerelease: false
